pipeline:
  build:
    image: maven
    commands:
      - mvn install -B
  mk-car:
    image: cofob/ipfs-tools
    commands:
      - ipfs-car --wrapWithDirectory false --pack target/ --output target.car
  pin-web3:
    image: cofob/node-hugo-jq
    commands:
      - |
        curl -X 'POST' \
          'https://api.web3.storage/car' \
          -H 'accept: application/json' \
          -H "Authorization: Bearer $JWT" \
          -H 'Content-Type: application/vnd.ipld.car' \
          --data-binary '@target.car' | jq -r .cid > cid.txt
      - echo "https://$(cat cid.txt).ipfs.ipfsqr.ru/"
    secrets: [ JWT ]
